env:
  browser: true
  es2020: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - prettier
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: { 'prettier/prettier': 'error' }
