default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

development:
  <<: *default
  database: danmu_classroom_development
  username: aaron
  password: '0417'
  host: localhost
  port: 5432

test:
  <<: *default
  database: danmu_classroom_test
  username: aaron
  password: '0417'
  host: localhost
  port: 5432

production:
  url: <%= ENV['DATABASE_URL'] || Rails.application.credentials.production[:database_url] %>
